name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  web:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npm run lint --if-present
      - run: npm run build --if-present

      - name: E2E (Cypress)
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: http://localhost:5173
          wait-on-timeout: 120
          browser: chrome

      - name: Install LHCI
        run: npm i -D @lhci/cli start-server-and-test

      - name: Lighthouse (preview de build)
        run: npx start-server-and-test "npm run preview -- --port 4173" http://localhost:4173 "npx lhci autorun --config=.lighthouserc.json"

      - name: Upload Lighthouse reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse
          path: lhci
